---
- name: Install Plasma
  community.general.pacman:
    name:
      - plasma
      - plasma-nm
      - dolphin
      - dolphin-plugins
      - kde-system-meta
      - kde-utilities-meta
      - sddm
      - spectacle
    state: present
  become: true

- name: Start systemd service - sddm
  ansible.builtin.systemd:
    name: sddm.service
    state: started
    enabled: yes
  become: true

