---
#
# User configuration
#
user:
  name: logan
  full_name: "Logan Marchione"
  primary_group: users
  additional_groups: wheel
  shell: /bin/zsh
  # See country list by running `reflector --list-countries`
  country: "United States"

git:
  name: "{{ user['full_name'] }}"
  email_b64: "bG9nYW5AbG9nYW5tYXJjaGlvbmUuY29t"
  # can be "cache", "store", "osxkeychain", or "manager"
  helper: "cache"

#
# Miscellaneous
#

# only AMD or Intel GPUs are currently supported
# true or false
install_gpu_drivers: true

# desktop environment to install
# "kde" or "gnome"
desktop: kde

# only AMD or Intel CPUs are currently supported
# true or false
install_microcode: true

# whether to enable printing/scanning or not
# true or false
enable_printing: true

# whether to detect the scanner or not
# true or false
detect_scanner: true

# whether to enable bluetooth or not
# true or false
enable_bluetooth: false

# how many parallel downloads to run at once
pacman:
  parallel_downloads: 10

# set aur helper
# supported helpers are here https://github.com/kewlfft/ansible-aur#kewlfftauraur-module
aur_helper: yay

#
# Services
#

# if not using LVM, disable it
# true or false
disable_lvm: true

# if not using systemd homed, disable it
# true or false
disable_systemd_homed: true

#
# Packages
#
packages:
  - alsa-utils
  - alsa-plugins
  - bash
  - bash-completion
  - cadaver
  - chromium
  - code
  - curl
  - docker
  - docker-compose
  - e2fsprogs
  - firefox
  - flameshot
  - flatpak
  - fwupd
  - gnupg
  - gparted
  - gvfs
  - gvfs-smb
  - hugo
  - htop
  - inkscape
  - inetutils
  - iotop
  - iperf3
  - iputils
  - jq
  - keepassxc
  - libreoffice-fresh
  - linux-firmware
  - man
  - man-db
  - man-pages
  - minicom
  - ncdu
  - neofetch
  - networkmanager
  - ntfs-3g
  - openresolv
  - openssh
  - openvpn
  - picocom
  - pipewire
  - pipewire-alsa
  - pipewire-pulse
  - pkgstats
  - qbittorrent
  - remmina
  - rsync
  - screen
  - solaar
  - sudo
  - texmaker
  - texlive-most
  - thunar
  - thunderbird
  - tree
  - usbutils
  - unzip
  - vi
  - vim
  - vlc
  - wget
  - wireguard-tools
  - wpa_supplicant
  - xfsprogs
  - youtube-dl
  - zip
  - zsh
  - zsh-completions
  - zstd

aur_packages:
  - 7-zip-bin
  - etcher-bin
  - ledger-live-bin
  - ledger-udev
  - m64py
  - rpi-imager-bin
  - svgo
  - unrar-free
  - ventoy-bin

flatpaks:
  - com.discordapp.Discord
  - com.github.tchx84.Flatseal
  - com.slack.Slack
  - com.spotify.Client
  - com.valvesoftware.Steam
  - com.valvesoftware.Steam.CompatibilityTool.Proton
  - org.gtk.Gtk3theme.Adwaita-dark
  - org.gtk.Gtk3theme.Yaru-dark
  - org.gtk.Gtk3theme.Yaru-light

base_fonts:
  - adobe-source-code-pro-fonts
  - adobe-source-sans-pro-fonts
  - adobe-source-serif-pro-fonts
  - noto-fonts
  - noto-fonts-emoji
  - ttf-anonymous-pro
  - ttf-dejavu
  - otf-cascadia-code
  - ttf-cascadia-code
  - ttf-hack

vscode_extension_list:
  - ms-python.python
  - ms-azuretools.vscode-docker
  - redhat.vscode-yaml
  - redhat.ansible
  - vscode-icons-team.vscode-icons
  - HashiCorp.terraform
  - arcticicestudio.nord-visual-studio-code
  - donjayamanne.githistory
  - eamodio.gitlens
  - mhutchie.git-graph

printing_scanning_packages:
  - cups
  - cups-pdf
  - sane
  - sane-airscan
  - simple-scan

printing_scanning_aur_packages:
  - brlaser-git
  - brscan4
