---
#
# User configuration
#
user:
  name: carlos
  full_name: "Carlos Herrera"
  primary_group: users
  additional_groups: docker,wheel
  # /bin/bash or /bin/zsh
  shell: /bin/zsh
  # See country list by running `reflector --list-countries`
  country: "United States"

git:
  name: "{{ user['full_name'] }}"
  # obfuscated a little so bots won't find it
  email_b64: "Y2hlcnJlcmFzY3pAZ21haWwuY29tCg=="
  # can be "cache", "store", "osxkeychain", or "manager"
  helper: "cache"
  # can be "true" or "false"
  rebase: "true"
  # see this https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---color-movedltmodegt
  colorMoved: "zebra"
  autoSetupRemote: true

#
# Miscellaneous
#

# desktop environment to install
# "kde" or "gnome"
desktop: kde

theme:
  hyprland: tokyo-night-sddm
  kde: tokyo-night-sddm

compositor_command:
  hyprland: Hyprland
  kde: kde

# only AMD or Intel CPUs are currently supported
# true or false
install_microcode: true

# whether to enable printing/scanning or not
# true or false
enable_printing: true

# whether to detect the scanner or not
# true or false
detect_scanner: true

# whether to enable bluetooth or not
# true or false
enable_bluetooth: false

# whether to install laptop tools
# true or false
laptop: true

# how many parallel downloads to run at once
pacman:
  parallel_downloads: 10

# set aur helper
# supported helpers are here https://github.com/kewlfft/ansible-aur#kewlfftauraur-module
aur_helper: yay

#
# Services
#

# Set up automatic btrfs snapshots with Timeshift.
# MUST HAVE GRUB SET UP AS BOOTLOADER!
# Will run automated snapshots before every package update with
# `timeshift-autosnap` and make them appear as boot options.
enable_auto_btrfs_snapshots: true

# if not using LVM, disable it
# true or false
disable_lvm: false

# if not using systemd homed, disable it
# true or false
disable_systemd_homed: true

#
# Packages
#
packages:
  - ansible-lint
  - alacritty
  - alsa-utils
  - alsa-plugins
  - alsa-firmware
  - bash
  - bash-completion
  - bitwarden
  - chromium
  - curl
  - docker
  - docker-compose
  - e2fsprogs
  - firefox
  - flatpak
  - fwupd
  - fzf
  - git
  - gnupg
  - go
  - gparted
  - gvfs
  - gvfs-smb
  - htop
  - inetutils
  - intellij-idea-community-edition
  - iotop
  - iperf3
  - iputils
  - jq
  - krita
  - kubectl
  - libinput
  - linux-firmware
  - man
  - man-db
  - man-pages
  - minicom
  - ncdu
  - neofetch
  - neovim
  - networkmanager
  - nodejs
  - ntfs-3g
  - obs-studio
  - obsidian
  # - openresolv
  - openssh
  - openvpn
  - picocom
  - pipewire
  - pipewire-alsa
  - pkgstats
  - qbittorrent
  - rsync
  - ruby
  - samba
  - solaar
  - sudo
  - thunar
  - tmux
  - tree
  - unzip
  - vi
  - vim
  - vlc
  - wget
  - wireguard-tools
  - wireplumber
  - wpa_supplicantcom.parsecgaming.parsec
  # Needed for GTK apps that run as Flatpaks
  - xdg-desktop-portal-gtk
  - xfsprogs
  - zip
  - zoxide
  - zsh
  - zsh-completions
  - zstd

aur_packages:
  - 7-zip-bin
  - brave-bin
  - davinci-resolve
  - mailspring-bin
  - mullvad-vpn-bin
  - protonup-qt-bin
  - sddm-theme-tokyo-night
  - ventoy-bin
  - yt-dlp


snapshot_dependencies:
  packages:
    - timeshift
    - grub-btrfs
  aur_packages:
    - timeshift-autosnap

flatpaks:
  - com.usebruno.Bruno
  - com.discordapp.Discord
  - com.github.tchx84.Flatseal
  - com.slack.Slack
  - com.spotify.Client
  - com.parsecgaming.parsec
  - com.valvesoftware.Steam
  - com.valvesoftware.Steam.CompatibilityTool.Proton
  - fr.handbrake.ghb
  - org.bunkus.mkvtoolnix-gui
  - org.freedesktop.Platform.ffmpeg-full/x86_64/23.08
  - org.freedesktop.Platform.openh264/x86_64/2.3.0
  - org.gimp.GIMP
  - io.github.flattool.Warehouse
  - org.gtk.Gtk3theme.Adwaita-dark
  - org.gtk.Gtk3theme.Yaru-dark
  - org.gtk.Gtk3theme.Yaru-light
  - org.libreoffice.LibreOffice
  - org.remmina.Remmina
  - us.zoom.Zoom
  # See other themes here
  # flatpak remote-ls flathub | grep org.gtk.Gtk3theme

ruby_gems:
  - fusuma

fusuma_configs:
  kde:
    fusuma-kde.yml
  gnome:
    fusuma-gnome-popos.yml
base_fonts:
  - adobe-source-code-pro-fonts
  - adobe-source-sans-pro-fonts
  - adobe-source-serif-pro-fonts
  - gnu-free-fonts
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - powerline-fonts
  - ttf-anonymous-pro
  - ttf-dejavu
  - otf-cascadia-code
  - ttf-cascadia-code
  - ttf-hack

printing_scanning_packages:
  - cups
  - cups-pdf
  - sane
  - sane-airscan
  - simple-scan

printing_scanning_aur_packages:
  - brlaser-git
  - brscan4
