---
- name: Installing AUR helper
  kewlfft.aur.aur:
    name: "{{ aur_helper }}"

- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'

- name: Install AUR packages
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    state: present
    use: "{{ aur_helper }}"
  become: true
  become_user: aur_builder

- name: Install Gnome AUR packages
  when: desktop == "gnome"
  kewlfft.aur.aur:
    name: "extension-manager"
    state: present
    use: "{{ aur_helper }}"
  become: true
  become_user: aur_builder

- name: Set up fusuma for better trackpad support
  become: true
  when: desktop in ["gnome", "kde"]
  block:
    - name: Set fusuma dir
      ansible.builtin.set_fact:
        - fusuma_path: "{{ ansible_env.HOME }}/.config/fusuma"
    - name: "Add user to input group - {{ ansible_user_id }}"
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: input
        append: yes
    - name: Ensure fusuma config dir exists
      ansible.builtin.file:
        path: "{{ fusuma_path }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0766"
    - name: "Copy fusuma config file - {{ desktop }}"
      ansible.builtin.copy:
        src: "fusuma-{{ desktop }}.yml"
        dest: "{{ fusuma_path }}/config.yml"
        mode: "0766"
