---
- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  become: true

- name: Install flatpaks
  community.general.flatpak:
    name: "{{ flatpaks }}"
    state: present
    remote: flathub
  become: true

- name: Override theme
  ansible.builtin.shell: flatpak override --user --env=GTK_THEME=Adwaita:dark com.github.tchx84.Flatseal  # noqa command-instead-of-shell
  changed_when: no
