---
- hosts: all
  roles:
    - { role: 01_host_info }
    - { role: 02_basics }
    - { role: 03_x }
    - { role: 04_desktop }
    - { role: 05_packages }
    - { role: 06_microcode }
    - { role: 07_printing_scanning }
    - { role: 08_users }
    - { role: 09_bluetooth, when: enable_bluetooth }
