---
- name: Install AUR helper (yay)
  kewlfft.aur.aur:
    name: yay
  become: true

- name: Install AUR packages
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    state: present
    use: yay
  become: true
