---
- name: Install AUR helper "{{ aur_helper }}"
  kewlfft.aur.aur:
    name: "{{ aur_helper }}"
  become: true

- name: Install AUR packages
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    state: present
    use: "{{ aur_helper }}"
  become: true
