---
- name: Install packages
  community.general.pacman:
    name:
      - bash
      - chromium
      - code
      - conky
      - e2fsprogs
      - filelight
      - firefox
      - flatpak
      - fwupd
      - gparted
      - gvfs
      - gvfs-smb
      - gwenview
      - htop
      - inkscape
      - iputils
      - jq
      - kate
      - kcalc
      - keepassxc
      - libreoffice-fresh
      - linux-firmware
      - ncdu
      - neofetch
      - openresolv
      - openssh
      - openvpn
      - p7zip
      - pacman-contrib
      - qbittorrent
      - rsync
      - solaar
      - spectacle
      - sudo
      - texmaker
      - texlive-most
      - thunar
      - thunderbird
      - usbutils
      - unzip
      - wget
      - wireguard-tools
      - vi
      - vim
      - vlc
      - xfsprogs
      - zsh
    state: present
  become: true

- name: Install fonts
  community.general.pacman:
    name:
      - adobe-source-code-pro-fonts
      - adobe-source-sans-pro-fonts
      - adobe-source-serif-pro-fonts
      - noto-fonts
      - noto-fonts-emoji
      - ttf-anonymous-pro
      - ttf-dejavu
      - otf-cascadia-code
      - ttf-cascadia-code
      - ttf-hack
    state: present
  become: true

- name: Start systemd service - paccache.timer
  ansible.builtin.systemd:
    name: paccache.timer
    state: started
    enabled: yes
  become: true

- import_tasks: aur.yml
- import_tasks: flatpak.yml
