---
- name: Install packages
  community.general.pacman:
    name:
      - bash
      - bash-completion
      - chromium
      - code
      - conky
      - curl
      - docker
      - e2fsprogs
      - filelight
      - firefox
      - flameshot
      - flatpak
      - fwupd
      - gnupg
      - gparted
      - gvfs
      - gvfs-smb
      - gwenview
      - hugo
      - htop
      - inkscape
      - inetutils
      - iotop
      - iputils
      - jq
      - kate
      - kcalc
      - keepassxc
      - libreoffice-fresh
      - linux-firmware
      - man
      - man-db
      - man-pages
      - minicom
      - ncdu
      - neofetch
      - networkmanager
      - openresolv
      - openssh
      - openvpn
      - p7zip
      - pacman-contrib
      - picocom
      - pkgstats
      - qbittorrent
      - remmina
      - rsync
      - screen
      - solaar
      - spectacle
      - sudo
      - texmaker
      - texlive-most
      - thunar
      - thunderbird
      - tree
      - usbutils
      - unzip
      - wget
      - wireguard-tools
      - vi
      - vim
      - vlc
      - wpa_supplicant
      - xfsprogs
      - youtube-dl
      - zip
      - zsh
      - zsh-completions
      - zstd
    state: present
  become: true

- name: Install fonts
  community.general.pacman:
    name:
      - adobe-source-code-pro-fonts
      - adobe-source-sans-pro-fonts
      - adobe-source-serif-pro-fonts
      - noto-fonts
      - noto-fonts-emoji
      - ttf-anonymous-pro
      - ttf-dejavu
      - otf-cascadia-code
      - ttf-cascadia-code
      - ttf-hack
    state: present
  become: true

- name: Start systemd service - paccache.timer
  ansible.builtin.systemd:
    name: paccache.timer
    state: started
    enabled: yes
  become: true

- import_tasks: aur.yml
- import_tasks: flatpak.yml
