---
- name: Install Xorg
  community.general.pacman:
    name:
      - xorg-server
    state: present
  become: true

- name: Detect GPU
  ansible.builtin.shell: set -o pipefail && lspci -v | grep -A1 -e VGA -e 3D  # noqa command-instead-of-shell
  register: gpu_result
  changed_when: no

- name: Install GPU drivers
  block:
    - name: Install GPU drivers (AMD)
      community.general.pacman:
        name:
          - libva-mesa-driver
          - mesa
          - mesa-vdpau
          - vulkan-radeon
          - xf86-video-amdgpu
        state: present
      become: true
      when: "'Radeon' in gpu_result.stdout"

    - name: Install GPU drivers (Intel)
      community.general.pacman:
        name:
          - mesa
          - vulkan-intel
          - xf86-video-intel
        state: present
      become: true
      when: "'Intel' in gpu_result.stdout"
  when: install_gpu_drivers == true
