---
- name: Install desktop environment
  become: true
  when: desktop == "kde"
  block:
    - name: Install Plasma
      community.general.pacman:
        name:
          - plasma-meta
          # - plasma-wayland-session
          - kde-graphics-meta
          - kde-multimedia-meta
          - kde-network-meta
          - kde-pim-meta
          - kde-sdk-meta
          - kde-system-meta
          - kde-utilities-meta
          - sddm
          - xdg-desktop-portal-kde
        state: present

- name: Install desktop environment
  when: desktop == "gnome"
  become: true
  block:
    - name: Install Gnome
      community.general.pacman:
        name:
          - gnome
          - gnome-shell
          - gnome-control-center
          - gdm
          - xdg-desktop-portal-gnome
          - gnome-tweaks
        state: present

    - name: Stop systemd service - sddm.service
      ansible.builtin.systemd:
        name: sddm.service
        enabled: no
      ignore_errors: true
      register: ignore_errors_register

    - name: Start systemd service - gdm.service
      ansible.builtin.systemd:
        name: gdm.service
        enabled: yes

- name: Install desktop environment
  when: desktop == "hyprland"
  become: true
  block:
    - name: Install hyprland
      community.general.pacman:
        name:
          - hyprland
          - waybar
          - sddm
        state: present

- name: Set up SDDM for DE
  when: desktop == "hyprland" or desktop == "kde"
  become: true
  block:
    - name: Set up SDDM conf file
      ansible.builtin.template:
        src: sddm.conf.jinja
        dest: /etc/sddm.conf
        backup: no
        owner: root
        group: root
        mode: 0644

    - name: Stop systemd service - gdm.service
      ansible.builtin.systemd:
        name: gdm.service
        enabled: no
      ignore_errors: true
      register: ignore_errors_register

    - name: Start systemd service - sddm.service
      ansible.builtin.systemd:
        name: sddm.service
        enabled: yes

- name: Import KDE shortcuts
  when: desktop == "kde"
  ansible.builtin.pause:
    prompt: |
      "Import KDE shortcuts if desired by pressing `Meta` -> "Shortcuts" -> clicking the import button -> select KDE Default for 3 Modifier Keys. The backed up shortcuts file can be found in:"
      "{{ playbook_dir }}/04_desktop/files/kde-shortcuts.kksrc"
      "Press [ENTER] once completed."
    echo: no
