---
- name: Install desktop environment
  block:
    - name: Install Plasma
      community.general.pacman:
        name:
          - plasma-meta
          - plasma-wayland-session
          - kde-graphics-meta
          - kde-multimedia-meta
          - kde-network-meta
          - kde-pim-meta
          - kde-sdk-meta
          - kde-system-meta
          - kde-utilities-meta
          - sddm
        state: present
      become: true

    - name: Start systemd service - sddm.service
      ansible.builtin.systemd:
        name: sddm.service
        state: started
        enabled: yes
      become: true
  when: desktop == "kde"

- name: Install desktop environment
  block:
    - name: Install Gnome
      community.general.pacman:
        name:
          - gnome
          - gdm
        state: present
      become: true

    - name: Start systemd service - gdm.service
      ansible.builtin.systemd:
        name: gdm.service
        state: started
        enabled: yes
      become: true
  when: desktop == "gnome"
