---
- name: Install printing and scanning packages
  community.general.pacman:
    name: "{{ printing_scanning_packages }}"
  become: true

- name: Install printing and scanning packages (AUR)
  kewlfft.aur.aur:
    name: "{{ printing_scanning_aur_packages }}"
    state: present
    use: "{{ aur_helper }}"

- name: Start systemd service - cups.socket
  ansible.builtin.systemd:
    name: cups.socket
    state: started
    enabled: yes
  become: true

- name: Detect scanner
  ansible.builtin.shell: set -o pipefail && scanimage -L  # noqa command-instead-of-shell
  register: scanimage_result
  changed_when: no
  when: detect_scanner

- name: Display scanner
  ansible.builtin.debug:
    msg:
      - "Detected the scanner below"
      - "{{ scanimage_result.stdout }}"
  when: detect_scanner
