---
- name: Create user
  ansible.builtin.user:
    name: "{{ user.name }}"
    comment: "{{ user.full_name }}"
    groups: "{{ user.additional_groups }}"
    append: yes
    shell: "{{ user.shell }}"
    state: present
  become: true

- name: Git config name
  git_config:
    name: user.name
    scope: global
    value: "{{ git.name }}"

- name: Git config email
  git_config:
    name: user.email
    scope: global
    value: "{{ git.email_b64 | b64decode }}"

- name: Git config credential helper
  git_config:
    name: credential.helper
    scope: global
    value: "{{ git.helper }}"

- name: Git config credential helper
  git_config:
    name: credential.helper
    scope: global
    value: "cache"

- name: Install VS Code extensions
  ansible.builtin.shell: code --install-extension {{ item }}  # noqa command-instead-of-shell
  with_items: "{{ vscode_extension_list }}"

- name: Get dotfiles
  ansible.builtin.get_url:
    url: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0644
    owner: "{{ user.name }}"
    group: "{{ user.primary_group }}"
  with_items:
    - { src: 'https://raw.githubusercontent.com/loganmarchione/dotfiles/main/.zshrc', dest: '/home/logan/.zshrc' }
    - { src: 'https://raw.githubusercontent.com/loganmarchione/dotfiles/main/.vimrc', dest: '/home/logan/.vimrc' }
    - { src: 'https://raw.githubusercontent.com/loganmarchione/dotfiles/main/.bashrc', dest: '/home/logan/.bashrc' }

- name: Update makepkg configuration file
  ansible.builtin.template:
    src: makepkg.conf
    dest: "/home/{{ user.name }}/.makepkg.conf"
    backup: no
    owner: "{{ user.name }}"
    group: "{{ user.primary_group }}"
    mode: 0644

- name: Mask systemd services - lvm
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: yes
  become: true
  with_items:
    - lvm2-lvmetad.service
    - lvm2-lvmetad.socket
    - lvm2-monitor.service
  when: disable_lvm == true

- name: Mask systemd services - systemd homed
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: yes
  become: true
  with_items:
    - systemd-homed.service
    - systemd-userdbd.service
    - systemd-userdbd.socket
  when: disable_systemd_homed == true
