---
- name: Git config name
  git_config:
    name: user.name
    scope: global
    value: "{{ git.name }}"

- name: Git config email
  git_config:
    name: user.email
    scope: global
    value: "{{ git.email | b64decode }}"

- name: Git config credential helper
  git_config:
    name: credential.helper
    scope: global
    value: "cache"

- name: Get dotfiles
  ansible.builtin.get_url:
    url: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0644
    owner: logan
    group: users
  with_items:
    - { src: 'https://raw.githubusercontent.com/loganmarchione/dotfiles/main/.zshrc', dest: '/home/logan/.zshrc' }
    - { src: 'https://raw.githubusercontent.com/loganmarchione/dotfiles/main/.vimrc', dest: '/home/logan/.vimrc' }
    - { src: 'https://raw.githubusercontent.com/loganmarchione/dotfiles/main/.bashrc', dest: '/home/logan/.bashrc' }
